from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    op.create_table(
        'users',
        sa.Column('id', sa.UUID(), nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('email', sa.String(length=255), nullable=False, unique=True),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.CheckConstraint("role IN ('admin', 'user')", name='role_check'),
    )

    op.create_table(
        'tournaments',
        sa.Column('id', sa.UUID(), nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('location', sa.String(length=255), nullable=False),
        sa.Column('date', sa.DATE(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.UniqueConstraint('name', 'date', name='unique_name_date')
    )

    op.create_table(
        'matches',
        sa.Column('id', sa.UUID(), nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tournament_id', sa.UUID(), nullable=False),
        sa.Column('player1_id', sa.UUID(), nullable=False),
        sa.Column('player2_id', sa.UUID(), nullable=False),
        sa.Column('scheduled_time', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ondelete='CASCADE')
    )

    op.create_table(
        'scores',
        sa.Column('id', sa.UUID(), nullable=False, primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('match_id', sa.UUID(), nullable=False),
        sa.Column('player1_score', sa.Integer(), nullable=False),
        sa.Column('player2_score', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
        sa.CheckConstraint('player1_score >= 0', name='check_player1_score_positive'),
        sa.CheckConstraint('player2_score >= 0', name='check_player2_score_positive')
    )

    op.create_index(op.f('ix_tournaments_name'), 'tournaments', ['name'], unique=False)
    op.create_index(op.f('ix_tournaments_date'), 'tournaments', ['date'], unique=False)
    op.create_index(op.f('ix_matches_tournament_id'), 'matches', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_matches_scheduled_time'), 'matches', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_scores_match_id'), 'scores', ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_match_id'), table_name='scores')
    op.drop_index(op.f('ix_matches_scheduled_time'), table_name='matches')
    op.drop_index(op.f('ix_matches_tournament_id'), table_name='matches')
    op.drop_index(op.f('ix_tournaments_date'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_name'), table_name='tournaments')
    op.drop_table('scores')
    op.drop_table('matches')
    op.drop_table('tournaments')
    op.drop_table('users')
    # ### end Alembic commands ###